name 'awesome_customers_ubuntu'
maintainer 'Chris Diehl'
maintainer_email 'chris@diehlabs.com'
license 'all_rights'
description 'Installs/Configures awesome_customers_ubuntu'
long_description 'Installs/Configures awesome_customers_ubuntu'
version '0.1.1'

depends 'apt', '~> 4.0'
depends 'firewall', '~> 2.4'
depends 'httpd', '~> 0.4'
