name 'awesome_customers_database'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awesome_customers_database'
long_description 'Installs/Configures awesome_customers_database'
version '0.1.5'

depends 'apt', '~>4.0'
depends 'mysql', '~>8.0'
depends 'mysql2_chef_gem', '~> 1.1'
depends 'database', '~> 5.1'
